// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc246;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainFrontLeftMotor;
    public static SpeedController driveTrainFrontRightMotor;
    public static SpeedController driveTrainBackLeftMotor;
    public static SpeedController driveTrainBackRightMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static SpeedController armArmMotor;
    public static SpeedController shooterShooterMotor;
    public static DoubleSolenoid shooterDoubleSolenoidShooter1;
    public static DoubleSolenoid shooterDoubleSolenoidShooter2;
    public static DoubleSolenoid shooterDoubleSolenoidShooter3;
    public static DoubleSolenoid shooterDoubleSolenoidShooter4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeftMotor = new Victor(1, 1);
	LiveWindow.addActuator("Drive Train", "Front Left Motor", (Victor) driveTrainFrontLeftMotor);
        
        driveTrainFrontRightMotor = new Victor(1, 2);
	LiveWindow.addActuator("Drive Train", "Front Right Motor", (Victor) driveTrainFrontRightMotor);
        
        driveTrainBackLeftMotor = new Victor(1, 3);
	LiveWindow.addActuator("Drive Train", "Back Left Motor", (Victor) driveTrainBackLeftMotor);
        
        driveTrainBackRightMotor = new Victor(1, 4);
	LiveWindow.addActuator("Drive Train", "Back Right Motor", (Victor) driveTrainBackRightMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainFrontLeftMotor, driveTrainBackLeftMotor,
              driveTrainFrontRightMotor, driveTrainBackRightMotor);
	
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        armArmMotor = new Victor(1, 5);
	LiveWindow.addActuator("Arm", "Arm Motor", (Victor) armArmMotor);
        
        shooterShooterMotor = new Victor(1, 6);
	LiveWindow.addActuator("Shooter", "Shooter Motor", (Victor) shooterShooterMotor);
        
        shooterDoubleSolenoidShooter1 = new DoubleSolenoid(1, 1, 2);      
	
        
        shooterDoubleSolenoidShooter2 = new DoubleSolenoid(1, 3, 4);      
	
        
        shooterDoubleSolenoidShooter3 = new DoubleSolenoid(1, 5, 6);      
	
        
        shooterDoubleSolenoidShooter4 = new DoubleSolenoid(1, 7, 8);      
	
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
