// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc246.subsystems;

import org.usfirst.frc246.RobotMap;
import org.usfirst.frc246.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController shooterMotor = RobotMap.shooterShooterMotor;
    DoubleSolenoid doubleSolenoidShooter1 = RobotMap.shooterDoubleSolenoidShooter1;
    DoubleSolenoid doubleSolenoidShooter2 = RobotMap.shooterDoubleSolenoidShooter2;
    DoubleSolenoid doubleSolenoidShooter3 = RobotMap.shooterDoubleSolenoidShooter3;
    DoubleSolenoid doubleSolenoidShooter4 = RobotMap.shooterDoubleSolenoidShooter4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void intake()
    {
        shooterMotor.set(-1);
    }
    public void shooterOff()
    {
        shooterMotor.set(0);
        doubleSolenoidShooter1.set(DoubleSolenoid.Value.kReverse);
        doubleSolenoidShooter2.set(DoubleSolenoid.Value.kReverse);
        doubleSolenoidShooter3.set(DoubleSolenoid.Value.kReverse);
        doubleSolenoidShooter4.set(DoubleSolenoid.Value.kReverse);
    }
    public void prepareToShoot()
    {
        shooterMotor.set(1);
    }
    public void shoot()
    {
        doubleSolenoidShooter1.set(DoubleSolenoid.Value.kForward);
        doubleSolenoidShooter2.set(DoubleSolenoid.Value.kForward);
        doubleSolenoidShooter3.set(DoubleSolenoid.Value.kForward);
        doubleSolenoidShooter4.set(DoubleSolenoid.Value.kForward);
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new OffShooter());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

